name: Build APK with Buildozer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip git python3-pip python3-setuptools libtool autoconf automake build-essential
          pip install --upgrade pip
          pip install buildozer cython

      - name: Set up Android SDK
        run: |
          sudo apt-get install -y openjdk-8-jdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip
          unzip commandlinetools-linux-8092744_latest.zip -d android-sdk
          echo "y" | android-sdk/tools/bin/sdkmanager --licenses
          android-sdk/tools/bin/sdkmanager "platforms;android-29" "build-tools;29.0.3"

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: bin/*.apk
